"""
List of districts in Yandex.Local
"""

__all__ = ['DISTRICTS']


DISTRICTS = [
    {"id": 23, "slug": "moscow/akademichesky", "name": "Академический", "membersCount": 27111},
    {"id": 61, "slug": "moscow/alekseyevsky", "name": "Алексеевский", "membersCount": 20170},
    {"id": 107, "slug": "moscow/altufyevsky", "name": "Алтуфьевский", "membersCount": 21879},
    {"id": 83, "slug": "moscow/arbat", "name": "Арбат", "membersCount": 26747},
    {"id": 38, "slug": "moscow/aeroport", "name": "Аэропорт", "membersCount": 25377},
    {"id": 90, "slug": "moscow/babushkinsky", "name": "Бабушкинский", "membersCount": 25277},
    {"id": 53, "slug": "moscow/basmanny", "name": "Басманный", "membersCount": 58676},
    {"id": 94, "slug": "moscow/begovoy", "name": "Беговой", "membersCount": 28195},
    {"id": 108, "slug": "moscow/beskudnikovsky", "name": "Бескудниковский",
     "membersCount": 19778},
    {"id": 87, "slug": "moscow/bibirevo", "name": "Бибирево", "membersCount": 21577},
    {"id": 13, "slug": "moscow/biryulyovo-vostochnoye", "name": "Бирюлёво Восточное",
     "membersCount": 25821},
    {"id": 9, "slug": "moscow/biryulyovo-zapadnoye", "name": "Бирюлёво Западное",
     "membersCount": 21433},
    {"id": 14, "slug": "moscow/bogorodskoye", "name": "Богородское", "membersCount": 19697},
    {"id": 144, "slug": "moscow/brateyevo", "name": "Братеево", "membersCount": 25334},
    {"id": 60, "slug": "moscow/butyrsky", "name": "Бутырский", "membersCount": 26813},
    {"id": 19, "slug": "moscow/veshnyaki", "name": "Вешняки", "membersCount": 35927},
    {"id": 121, "slug": "moscow/vnukovo", "name": "Внуково", "membersCount": 3795},
    {"id": 134, "slug": "moscow/voykovsky", "name": "Войковский", "membersCount": 20044},
    {"id": 117, "slug": "moscow/vostochnoye-degunino", "name": "Восточное Дегунино",
     "membersCount": 24393},
    {"id": 70, "slug": "moscow/vostochnoye-izmaylovo", "name": "Восточное Измайлово",
     "membersCount": 20175},
    {"id": 96, "slug": "moscow/vostochny", "name": "Восточный", "membersCount": 5313},
    {"id": 30, "slug": "moscow/vykhino-zhulebino", "name": "Выхино-Жулебино",
     "membersCount": 30363},
    {"id": 36, "slug": "moscow/gagarinsky", "name": "Гагаринский", "membersCount": 26184},
    {"id": 92, "slug": "moscow/golovinsky", "name": "Головинский", "membersCount": 29657},
    {"id": 21, "slug": "moscow/golyanovo", "name": "Гольяново", "membersCount": 30090},
    {"id": 42, "slug": "moscow/danilovsky", "name": "Даниловский", "membersCount": 51504},
    {"id": 74, "slug": "moscow/dmitrovsky", "name": "Дмитровский", "membersCount": 20993},
    {"id": 55, "slug": "moscow/donskoy", "name": "Донской", "membersCount": 30530},
    {"id": 45, "slug": "moscow/dorogomilovo", "name": "Дорогомилово", "membersCount": 38562},
    {"id": 57, "slug": "moscow/zamoskvorechye", "name": "Замоскворечье", "membersCount": 38339},
    {"id": 6, "slug": "moscow/zapadnoye-degunino", "name": "Западное Дегунино",
     "membersCount": 28613},
    {"id": 4, "slug": "moscow/zyuzino", "name": "Зюзино", "membersCount": 23839},
    {"id": 125, "slug": "moscow/zyablikovo", "name": "Зябликово", "membersCount": 22126},
    {"id": 48, "slug": "moscow/ivanovskoye", "name": "Ивановское", "membersCount": 30092},
    {"id": 47, "slug": "moscow/izmaylovo", "name": "Измайлово", "membersCount": 40733},
    {"id": 31, "slug": "moscow/kapotnya", "name": "Капотня", "membersCount": 11913},
    {"id": 26, "slug": "moscow/konkovo", "name": "Коньково", "membersCount": 29201},
    {"id": 8, "slug": "moscow/koptevo", "name": "Коптево", "membersCount": 16966},
    {"id": 103, "slug": "moscow/kosino-ukhtomsky", "name": "Косино-Ухтомский",
     "membersCount": 30337},
    {"id": 139, "slug": "moscow/kotlovka", "name": "Котловка", "membersCount": 21494},
    {"id": 155, "slug": "moscow/krasnoselsky", "name": "Красносельский", "membersCount": 35358},
    {"id": 78, "slug": "moscow/krylatskoye", "name": "Крылатское", "membersCount": 20783},
    {"id": 82, "slug": "moscow/kuzminki", "name": "Кузьминки", "membersCount": 29558},
    {"id": 68, "slug": "moscow/kuntsevo", "name": "Кунцево", "membersCount": 36257},
    {"id": 128, "slug": "moscow/kurkino", "name": "Куркино", "membersCount": 11229},
    {"id": 98, "slug": "moscow/levoberezhny", "name": "Левобережный", "membersCount": 24491},
    {"id": 24, "slug": "moscow/lefortovo", "name": "Лефортово", "membersCount": 37741},
    {"id": 135, "slug": "moscow/lianozovo", "name": "Лианозово", "membersCount": 17911},
    {"id": 11, "slug": "moscow/lomonosovsky", "name": "Ломоносовский", "membersCount": 23639},
    {"id": 137, "slug": "moscow/losinoostrovsky", "name": "Лосиноостровский",
     "membersCount": 18558},
    {"id": 16, "slug": "moscow/lyublino", "name": "Люблино", "membersCount": 38834},
    {"id": 104, "slug": "moscow/marfino", "name": "Марфино", "membersCount": 11520},
    {"id": 88, "slug": "moscow/maryina-roscha", "name": "Марьина Роща", "membersCount": 31624},
    {"id": 1, "slug": "moscow/maryino", "name": "Марьино", "membersCount": 33118},
    {"id": 133, "slug": "moscow/metrogorodok", "name": "Метрогородок", "membersCount": 25000},
    {"id": 3, "slug": "moscow/meshchansky", "name": "Мещанский", "membersCount": 37566},
    {"id": 91, "slug": "moscow/mitino", "name": "Митино", "membersCount": 23155},
    {"id": 69, "slug": "moscow/mozhaysky", "name": "Можайский", "membersCount": 27434},
    {"id": 136, "slug": "moscow/molzhaninovsky", "name": "Молжаниновский", "membersCount": 5260},
    {"id": 50, "slug": "moscow/moskvorechye-saburovo", "name": "Москворечье-Сабурово", "membersCount": 33485},
    {"id": 114, "slug": "moscow/nagatino-sadovniki", "name": "Нагатино-Садовники", "membersCount": 24210},
    {"id": 12, "slug": "moscow/nagatinsky-zaton", "name": "Нагатинский Затон", "membersCount": 26442},
    {"id": 85, "slug": "moscow/nagorny", "name": "Нагорный", "membersCount": 28217},
    {"id": 20, "slug": "moscow/nekrasovka", "name": "Некрасовка", "membersCount": 13355},
    {"id": 112, "slug": "moscow/nizhegorodsky", "name": "Нижегородский", "membersCount": 27930},
    {"id": 75, "slug": "moscow/novogireyevo", "name": "Новогиреево", "membersCount": 23279},
    {"id": 110, "slug": "moscow/novokosino", "name": "Новокосино", "membersCount": 15989},
    {"id": 22, "slug": "moscow/novo-peredelkino", "name": "Ново-Переделкино", "membersCount": 13169},
    {"id": 120, "slug": "moscow/obruchevsky", "name": "Обручевский", "membersCount": 35680},
    {"id": 65, "slug": "moscow/orekhovo-borisovo-severnoye", "name": "Орехово-Борисово Северное", "membersCount": 26706},
    {"id": 58, "slug": "moscow/orekhovo-borisovo-yuzhnoye", "name": "Орехово-Борисово Южное", "membersCount": 20200},
    {"id": 41, "slug": "moscow/ostankinsky", "name": "Останкинский", "membersCount": 36822},
    {"id": 15, "slug": "moscow/otradnoye", "name": "Отрадное", "membersCount": 31155},
    {"id": 119, "slug": "moscow/ochakovo-matveyevskoye", "name": "Очаково-Матвеевское",
     "membersCount": 34200},
    {"id": 52, "slug": "moscow/perovo", "name": "Перово", "membersCount": 28774},
    {"id": 123, "slug": "moscow/pechatniki", "name": "Печатники", "membersCount": 45398},
    {"id": 59, "slug": "moscow/pokrovskoye-streshnevo", "name": "Покровское-Стрешнево",
     "membersCount": 31349},
    {"id": 97, "slug": "moscow/preobrazhenskoye", "name": "Преображенское",
     "membersCount": 27711},
    {"id": 39, "slug": "moscow/presnensky", "name": "Пресненский", "membersCount": 59749},
    {"id": 86, "slug": "moscow/prospekt-vernadskogo", "name": "Проспект Вернадского",
     "membersCount": 26693},
    {"id": 46, "slug": "moscow/ramenki", "name": "Раменки", "membersCount": 43755},
    {"id": 25, "slug": "moscow/rostokino", "name": "Ростокино", "membersCount": 11527},
    {"id": 32, "slug": "moscow/ryazansky", "name": "Рязанский", "membersCount": 26896},
    {"id": 37, "slug": "moscow/savyolovsky", "name": "Савёловский", "membersCount": 20009},
    {"id": 56, "slug": "moscow/sviblovo", "name": "Свиблово", "membersCount": 18068},
    {"id": 73, "slug": "moscow/severnoye-butovo", "name": "Северное Бутово",
     "membersCount": 17820},
    {"id": 10, "slug": "moscow/severnoye-izmaylovo", "name": "Северное Измайлово",
     "membersCount": 26544},
    {"id": 81, "slug": "moscow/severnoye-medvedkovo", "name": "Северное Медведково",
     "membersCount": 21222},
    {"id": 28, "slug": "moscow/severnoye-tushino", "name": "Северное Тушино",
     "membersCount": 25735},
    {"id": 140, "slug": "moscow/severny", "name": "Северный", "membersCount": 7557},
    {"id": 101, "slug": "moscow/sokol", "name": "Сокол", "membersCount": 21627},
    {"id": 93, "slug": "moscow/sokolinaya-gora", "name": "Соколиная Гора", "membersCount": 30824},
    {"id": 89, "slug": "moscow/sokolniki", "name": "Сокольники", "membersCount": 36566},
    {"id": 43, "slug": "moscow/solntsevo", "name": "Солнцево", "membersCount": 18349},
    {"id": 76, "slug": "moscow/strogino", "name": "Строгино", "membersCount": 26263},
    {"id": 2, "slug": "moscow/tagansky", "name": "Таганский", "membersCount": 48379},
    {"id": 5, "slug": "moscow/tverskoy", "name": "Тверской", "membersCount": 61686},
    {"id": 99, "slug": "moscow/tekstilschiki", "name": "Текстильщики", "membersCount": 24352},
    {"id": 129, "slug": "moscow/tyoply-stan", "name": "Тёплый Стан", "membersCount": 24506},
    {"id": 44, "slug": "moscow/timiryazevsky", "name": "Тимирязевский", "membersCount": 31868},
    {"id": 71, "slug": "moscow/troparyovo-nikulino", "name": "Тропарёво-Никулино",
     "membersCount": 29970},
    {"id": 49, "slug": "moscow/filyovsky-park", "name": "Филёвский Парк", "membersCount": 31845},
    {"id": 106, "slug": "moscow/fili-davydkovo", "name": "Фили-Давыдково", "membersCount": 21615},
    {"id": 7, "slug": "moscow/khamovniki", "name": "Хамовники", "membersCount": 48780},
    {"id": 84, "slug": "moscow/khovrino", "name": "Ховрино", "membersCount": 20174},
    {"id": 111, "slug": "moscow/khoroshyovo-mnyovniki", "name": "Хорошёво-Мнёвники",
     "membersCount": 42504},
    {"id": 95, "slug": "moscow/khoroshyovsky", "name": "Хорошёвский", "membersCount": 33268},
    {"id": 27, "slug": "moscow/tsaritsyno", "name": "Царицыно", "membersCount": 22210},
    {"id": 51, "slug": "moscow/cheryomushki", "name": "Черёмушки", "membersCount": 30081},
    {"id": 79, "slug": "moscow/chertanovo-severnoye", "name": "Чертаново Северное",
     "membersCount": 21798},
    {"id": 35, "slug": "moscow/chertanovo-tsentralnoye", "name": "Чертаново Центральное",
     "membersCount": 26288},
    {"id": 18, "slug": "moscow/chertanovo-yuzhnoye", "name": "Чертаново Южное",
     "membersCount": 25598},
    {"id": 77, "slug": "moscow/schukino", "name": "Щукино", "membersCount": 25579},
    {"id": 63, "slug": "moscow/yuzhnoye-butovo", "name": "Южное Бутово", "membersCount": 24549},
    {"id": 40, "slug": "moscow/yuzhnoye-medvedkovo", "name": "Южное Медведково",
     "membersCount": 25566},
    {"id": 33, "slug": "moscow/yuzhnoye-tushino", "name": "Южное Тушино", "membersCount": 27279},
    {"id": 29, "slug": "moscow/yuzhnoportovy", "name": "Южнопортовый", "membersCount": 27710},
    {"id": 62, "slug": "moscow/yakimanka", "name": "Якиманка", "membersCount": 44123},
    {"id": 72, "slug": "moscow/yaroslavsky", "name": "Ярославский", "membersCount": 16975},
    {"id": 64, "slug": "moscow/yasenevo", "name": "Ясенево", "membersCount": 47108}]

if __name__ == "__main__":
    for i in DISTRICTS:
        print(i['slug'])
